### ISSUE TITLE
App crashing when pressing checkin button

### ISSUE THREAD

**Issue by anujacharya1** [TeamCinder/Cinder#5]
03-07 00:36:52.233 9419-9419/com.anuj.cinders E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.anuj.cinders, PID: 9419
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE cmp=com.google.android.GoogleCamera/com.android.camera.CaptureActivity (has extras) } from ProcessRecord{b4b7f2c 9419:com.anuj.cinders/u0a209} (pid=9419, uid=10209) with revoked permission android.permission.CAMERA
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2658)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
at android.app.Activity.startActivityForResult(Activity.java:3930)
at android.app.Activity.startActivityForResult(Activity.java:3890)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
at com.anuj.cinders.activities.VenueDetailActivity$2.onClick(VenueDetailActivity.java:151)
at android.view.View.performClick(View.java:5204)
at android.view.View$PerformClick.run(View.java:21153)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by zero-impact** [comment]
Could you tell me what version of Android you are running on? Seems like this might be related to Android M permissions.
This does not happen on my phone OR the emulator, so it is hard for me to debug.
